title: God of Carnage Publicity
client: Anthony Aston Players, Wake Forest University
datestamp: 2012-02-12
date: Winter 2011-2012
description: >
  A friend of mine from high school attends Wake Forest University, which has a
  vibrant student theatre group called the Anthony Aston Players. That spring, 
  they were planning to produce God of Carnage by Yasmina Reza, one of my
  favorite contemporary plays. At her recommendation, they hired me to design
  flyers and a poster for their production.
  
  The play is about two couples that meet after their children get into a fight
  on a playground and knock out a tooth. The meeting begins civilly, but the 
  finger pointing as to whose fault the injury is quickly devolves into
  antics worthy of a playground dust-up themselves.
  
  At the time, I had not had much experience designing for print, so this was
  a learning experience for me. I'm pretty happy with how it turned out
  nonetheless!
images: 
  - {filename: poster.png, alt: "The final poster design"}
  - {filename: teaser1.png, alt: "One of the teasers used to promote the show without naming it"}
  - {filename: teaser3.png, alt: "One of the teasers used to promote the show without naming it"}