title: Show Publicity
client: Bottom Line Theatre / The Druids
datestamp: 2012-09-01
date: Fall 2012
description: >
  As the (mysteriously titled) Cruise Director for Bottom Line Theatre, it was
  my job to design and distribute publicity materials for our season of shows.
  For a typical show, we use 8.5 x 11 flyers printed in black and white, which
  create constraints within which I had to work to create engaging designs.
  
  I worked with the directors and occasionally outside illustrators and 
  designers to create publicity for The Mike and Morgan Show by Raphael 
  Bob-Waksberg, Slippers on the Street by Paul Minx, and The Laramie Project 
  by Moises Kaufman and Tectonic Theatre Project.
images: 
  - {filename: slippers.jpg, alt: "Slippers on the Street"}
  - {filename: laramie.png, alt: "The Laramie Project"}
  - {filename: mikeandmorgan.jpg, alt: "The Mike and Morgan Show"}